<?php
return array(
    'jsMigrate'=>array(
        'baseUrl'=>'bootstrap/admin/js/',
        'js'=>array(
            'jquery-migrate-1.0.0.min.js',
            'jquery-ui-1.10.0.custom.min.js',
        ),
        'depends'=>array('jquery'),
    ),
    'statCircles'=>array(
        'baseUrl'=>'bootstrap/admin/js/',
        'js'=>array(
            'fullcalendar.min.js',
            'jquery.dataTables.min.js',
            'excanvas.js',
            'jquery.chosen.min.js',
            'jquery.uniform.min.js',
            'jquery.cleditor.min.js',
            'jquery.elfinder.min.js',
            'jquery.raty.min.js',
            'jquery.uploadify-3.1.min.js',
            'jquery.masonry.min.js',
            'jquery.knob.js',
            'jquery.sparkline.min.js',
        ),
        'depends'=>array('jquery'),
    ),
    'statPieChart'=>array(
        'baseUrl'=>'bootstrap/admin/js/',
        'js'=>array(
            'jquery.flot.min.js',
            'jquery.flot.pie.min.js',
            'custom.js',
        ),
        'depends'=>array('jquery'),
    ),
);